apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
   matchLabels:
      app: api
  replicas: 5 
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nginx:1.7.9
        ports:
        - containerPort: 80